# models/staging/sources.yml
version: 2

sources:
  - name: dbo
    database: H2EDGE
    schema: dbo
    tables:
      - name: courses
      - name: logs
      - name: flyway_schema_history
      - name: log_stages
      - name: runs
      - name: scraper_schemas
      - name: sources
      - name: urls
      - name: taxonomy01
      - name: course_taxonomy01